name: Release package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type (one of): patch, minor, major"
        # , prepatch, preminor, premajor, prerelease
        required: true
jobs:
  release_npm_package:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: "16"

      # Install dependencies (required by Run tests step)
      - name: Install dependencies
        run: npm install

      # Tests
      - name: Run tests
        run: npm test

      # Build
      - name: Build assets to publish
        run: npm run build

      # Bump package version
      # Use tag latest
      - name: Bump release version
        run: |
          echo "NEW_VERSION=$(npm --no-git-tag-version version $RELEASE_TYPE)" >> $GITHUB_ENV
          echo "RELEASE_TAG=latest" >> $GITHUB_ENV
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}

      # Publish version to public repository
      - name: Publish
        # run: npm publish --verbose --access public --tag {{ env.RELEASE_TAG }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}

      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "kevwe.samson@gmail.com"
          git config --global user.name "steveesamson-bot"
      # Push repository changes
      - name: Push changes to repository
        run: |
          git add .
          git commit -m "bumped version to ${{ env.NEW_VERSION}}"
          git push origin && git push --tags
